# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/pterXX/PrivatePod.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'IMLogin' do
    pod 'PrivateKit', :path =>'../PrivateKit'   #私有库, 常用分类
    pod 'IMBase', :path =>'../IMBase'           #基础类
    pod 'SVProgressHUD'
end
